apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: fib-go
spec:
  componentName: fib-go
  application: graphtuitous-as
  source:
    git:
      url: https://github.com/jduimovich/graphtuitous
      devfileUrl: devfiles/fib-go/devfile.yaml
  build:
    containerImage: quay.io/jduimovich0/fib-go
  
