apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: fib-node
spec:
  componentName: fib-node
  application: graphtuitous-as
  source:
    git:
      url: https://github.com/jduimovich/graphtuitous
      devfileUrl: devfiles/fib-node/devfile.yaml
  build:
    containerImage: quay.io/jduimovich0/fib-node
  
