apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: frontend
spec:
  componentName: frontend
  application: graphtuitous-as
  source:
    git:
      url: https://github.com/jduimovich/graphtuitous
      devfileUrl: devfiles/frontend/devfile.yaml
  build:
    containerImage: quay.io/jduimovich0/frontend
  
