apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: graphtuitous
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: app-e2e
    server: 'https://kubernetes.default.svc'
  source:
    path: components
    repoURL: 'https://github.com/northdepot/graphtuitous-in-app-studio-app-e2e-live-standard.git'
    targetRevision: HEAD
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
