apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: graphtuitous-extras
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: app-e2e
    server: 'https://kubernetes.default.svc'
  source:
    path: add-ons
    repoURL: ' https://github.com/jduimovich/appstudio-e2e.git'
    targetRevision: HEAD
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
